#!/bin/bash

# System Report Script
# By Elvis Osifo

# Blank line at the start of the report
echo ""

# Get the username, date, and time for the report header
USERNAME=$(whoami)
DATE_TIME=$(date)

# System Information
HOSTNAME=$(hostname)
OS_NAME=$(source /etc/os-release; echo "$PRETTY_NAME")
UPTIME=$(uptime -p)

# Hardware Information
if command -v lshw &> /dev/null; then
    CPU_INFO=$(lshw -class processor | grep "product" | head -n 1 | awk -F': ' '{print $2}')
    VIDEO_CARD=$(lshw -class display | grep "product" | awk -F': ' '{print $2}')
else
    CPU_INFO=$(cat /proc/cpuinfo | grep "model name" | head -n 1 | awk -F': ' '{print $2}')
    VIDEO_CARD=$(lspci | grep -i vga | awk -F': ' '{print $2}')
fi

RAM_SIZE=$(free -h | grep Mem | awk '{print $2}')
DISK_INFO=$(lsblk -o NAME,MODEL,SIZE | grep -v "NAME" | awk '{print $1, $2, $3}' | tr '\n' ', ')

# Network Information
FQDN=$(hostname -f)
HOST_ADDRESS=$(ip route get 1 | awk '{print $7}')
GATEWAY_IP=$(ip route | grep default | awk '{print $3}')
DNS_SERVER=$(grep nameserver /etc/resolv.conf | awk '{print $2}')

# System Status
LOGGED_IN_USERS=$(who | awk '{print $1}' | sort | uniq | tr '\n' ', ')
DISK_SPACE=$(df -h | grep -v "tmpfs" | awk '{print $6 " " $4}')
PROCESS_COUNT=$(ps -e | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'average: ' '{print $2}')
LISTENING_PORTS=$(ss -tuln | grep LISTEN | awk '{print $5}' | cut -d':' -f2 | sort -n | uniq | tr '\n' ', ')
UFW_STATUS=$(sudo ufw status | grep "Status" | awk '{print $2}')

# Output the report
echo "System Report generated by $USERNAME, $DATE_TIME"
echo ""
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $OS_NAME"
echo "Uptime: $UPTIME"
echo ""
echo "Hardware Information"
echo "--------------------"
echo "CPU: $CPU_INFO"
echo "RAM: $RAM_SIZE"
echo "Disk(s): $DISK_INFO"
echo "Video: $VIDEO_CARD"
echo ""
echo "Network Information"
echo "-------------------"
echo "FQDN: $FQDN"
echo "Host Address: $HOST_ADDRESS"
echo "Gateway IP: $GATEWAY_IP"
echo "DNS Server: $DNS_SERVER"
echo ""
echo "System Status"
echo "-------------"
echo "Users Logged In: $LOGGED_IN_USERS"
echo "Disk Space:"
echo "$DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVERAGES"
echo "Listening Network Ports: $LISTENING_PORTS"
echo "UFW Status: $UFW_STATUS"
echo ""

# Blank line at the end of the report
echo ""
